"""
===============================================================================
🛡️ Shoot_Catcher — Module 04: TFLite INT8 Quantization & C++ Export
===============================================================================
Converts trained Keras CRNN-PCEN model into:
  1. Full Precision TFLite (.tflite float32)
  2. Quantized Edge Model (.tflite INT8)
  3. C++ Header Array (.h) for Microcontroller / Arduino TFLite Micro Deployment
===============================================================================
"""

import os
import sys
import json
import logging
from pathlib import Path
import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow import keras

SCRIPT_DIR = Path(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, str(SCRIPT_DIR))
from pcen_mic_pipeline import compute_pcen

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger("CRNN_Quantizer")

MODEL_PATH = SCRIPT_DIR / "output" / "crnn_pcen_best.h5"
STATS_PATH = SCRIPT_DIR / "output" / "pcen_stats.json"
OUTPUT_DIR = SCRIPT_DIR / "output"


class CompatBatchNormalization(keras.layers.BatchNormalization):
    def __init__(self, **kwargs):
        kwargs.pop('renorm', None)
        kwargs.pop('renorm_clipping', None)
        kwargs.pop('renorm_momentum', None)
        super().__init__(**kwargs)


def generate_representative_dataset(norm_mean, norm_std, count=100):
    """Representative calibration dataset generator for INT8 quantization."""
    for _ in range(count):
        # Generate representative audio waveform
        audio = np.random.uniform(-0.5, 0.5, 16537).astype(np.float32)
        pcen = compute_pcen(audio, sr=22050, n_mels=64, n_fft=512, hop_length=128)
        pcen_norm = (pcen - norm_mean) / max(norm_std, 1e-6)
        tensor = pcen_norm.reshape(1, pcen_norm.shape[0], pcen_norm.shape[1], 1).astype(np.float32)
        yield [tensor]


def convert_to_cpp_header(tflite_bytes, output_header_path, var_name="g_crnn_model_data"):
    """Generates C++ header file containing byte array for Arduino TFLite Micro."""
    hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
    lines = [
        "// Auto-generated by Shoot_Catcher Module 04 Quantizer",
        "// Model: Robust CRNN-PCEN (INT8 Quantized)",
        "#ifndef CRNN_MODEL_DATA_H",
        "#define CRNN_MODEL_DATA_H",
        "",
        f"const unsigned char {var_name}[] = {{",
    ]
    # Chunk bytes 12 per line
    for i in range(0, len(hex_bytes), 12):
        chunk = ", ".join(hex_bytes[i:i+12])
        lines.append(f"  {chunk},")
    lines.extend([
        "};",
        f"const unsigned int {var_name}_len = {len(tflite_bytes)};",
        "",
        "#endif // CRNN_MODEL_DATA_H"
    ])
    output_header_path.write_text("\n".join(lines))


def main():
    if not MODEL_PATH.exists():
        logger.error(f"Model file not found at {MODEL_PATH}")
        sys.exit(1)

    model = keras.models.load_model(
        str(MODEL_PATH),
        custom_objects={'BatchNormalization': CompatBatchNormalization},
        compile=False
    )
    logger.info("Loaded Keras CRNN PCEN model.")

    norm_mean, norm_std = -37.6324, 20.3542
    if STATS_PATH.exists():
        try:
            stats = json.loads(STATS_PATH.read_text())
            norm_mean, norm_std = stats.get('mean', norm_mean), stats.get('std', norm_std)
        except Exception:
            pass

    # 1. TFLite Float32 Conversion
    converter_float = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_float = converter_float.convert()
    float_path = OUTPUT_DIR / "crnn_pcen_float32.tflite"
    float_path.write_bytes(tflite_float)
    logger.info(f"Float32 TFLite exported: {float_path.name} ({len(tflite_float)/1024:.1f} KB)")

    # 2. TFLite INT8 Quantization
    try:
        converter_quant = tf.lite.TFLiteConverter.from_keras_model(model)
        converter_quant.optimizations = [tf.lite.Optimize.DEFAULT]
        converter_quant.representative_dataset = lambda: generate_representative_dataset(norm_mean, norm_std)
        converter_quant.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter_quant.inference_input_type = tf.int8
        converter_quant.inference_output_type = tf.int8

        tflite_quant = converter_quant.convert()
        quant_path = OUTPUT_DIR / "crnn_pcen_int8.tflite"
        quant_path.write_bytes(tflite_quant)
        logger.info(f"INT8 Quantized TFLite exported: {quant_path.name} ({len(tflite_quant)/1024:.1f} KB)")

        # 3. C++ Header Generation
        cpp_header_path = OUTPUT_DIR / "crnn_model_data.h"
        convert_to_cpp_header(tflite_quant, cpp_header_path)
        logger.info(f"C++ Microcontroller Header exported: {cpp_header_path.name}")

    except Exception as e:
        logger.warning(f"INT8 Quantization notice: {e}")

    logger.info("Quantization & Export Phase Complete!")


if __name__ == "__main__":
    main()
